name: deploy-docs

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'which branch'
        required: true
        default: 'latest'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repository
      uses: actions/checkout@v2.3.4

    - name: clean docs
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script_stop: false
        script: |
          rm -rf /data/nginx/html/keycap/docs

    - name: publish blogs
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "docs"
        target: "/data/nginx/html/keycap/"
